### ISSUE TITLE
Рамки GBS и GB

### ISSUE THREAD

**Issue by Ivan788ru** [Rparadise-Team/BTN#2]
Уберите пожалуйста в настройках к GB и GBC рамки и сделайте полный экран игры, в виду того что экран приставки маленький рамки очень мешают. Спасибо

**Comment by albgr1979** [comment]
You can do it yourself:

1 - Remove the overlay from the RA quick menu.

2 - Go to the video settings and set the scaling to full screen.

3 - Save the content directory settings.

**Comment by Ivan788ru** [comment]
> Вы можете сделать это самостоятельно:
> 
> 1 — Удалить наложение из быстрого меню RA.
> 
> 2 - Зайдите в настройки видео и установите масштабирование на весь экран.
> 
> 3 — Сохраните настройки каталога содержимого.

Я так делал, но не даёт сохранить, поэтому попросил убрать рамки по умолчанию

**Comment by albgr1979** [comment]
> > Вы можете сделать это самостоятельно:
> 
> > 
> 
> > 1 — Удалить наложение из быстрого меню RA.
> 
> > 
> 
> > 2 - Зайдите в настройки видео и установите масштабирование на весь экран.
> 
> > 
> 
> > 3 — Сохраните настройки каталога содержимого.
> 
> 
> 
> Я так делал, но не даёт сохранить, поэтому попросил убрать рамки по умолчанию 

I just tried it and it works perfectly. There will be something you are not doing right.![image](https://github.com/Rparadise-Team/BTN/assets/110534038/1267c062-515b-4c52-bc1e-70f87d1c8d34)![image](https://github.com/Rparadise-Team/BTN/assets/110534038/6748424f-0655-4460-8d3d-53c1ff2d9d32)

**Comment by Ivan788ru** [comment]
> > > Вы можете сделать это самостоятельно:
> > 
> > 
> > > 
> > 
> > 
> > > 1 — Удалить наложение из быстрого меню RA.
> > 
> > 
> > > 
> > 
> > 
> > > 2 - Зайдите в настройки видео и установите масштабирование на весь экран.
> > 
> > 
> > > 
> > 
> > 
> > > 3 — Сохраните настройки содержимого каталога.
> > 
> > 
> > Я так делал, но не дай бог сохранить, поэтому попросил убрать рамки по умолчанию
> 
> Я только что попробовал, и это работает отлично. Будет что-то, что вы делаете не так.![изображение](https://private-user-images.githubusercontent.com/110534038/346329444-1267c062-515b-4c52-bc1e-70f87d1c8d34.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTQwODEsIm5iZiI6MTcyMDM1Mzc4MSwicGF0aCI6Ii8xMTA1MzQwMzgvMzQ2MzI5NDQ0LTEyNjdjMDYyLTUxNWItNGM1Mi1iYzFlLTcwZjg3ZDFjOGQzNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTIwMzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUyYTM3NGNkMGE0NjA5NmMxNDg5YzU4NDAxNmI0OTNhMDNkNTNiOWI0ODE3MGM0Y2RhMGRlMTRiYTQ3Njc5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2Zobd5yQs1LuilnSnUssu5c--h7PT-rNo_98mI4acfY)![изображение](https://private-user-images.githubusercontent.com/110534038/346329455-6748424f-0655-4460-8d3d-53c1ff2d9d32.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTQwODEsIm5iZiI6MTcyMDM1Mzc4MSwicGF0aCI6Ii8xMTA1MzQwMzgvMzQ2MzI5NDU1LTY3NDg0MjRmLTA2NTUtNDQ2MC04ZDNkLTUzYzFmZjJkOWQzMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTIwMzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2EwYzFlZTRiNzgyNGY3ZTE4YWNjMDIwZGRiY2RmZjE0YzZjNGNiZGM0NGMyNTY2NjIzY2IxNDljYWMxMzkxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lVl_OIpbQxl7VVsnNHb25KZY5BD8QGB7hGQ2nH28Uqg)

Можете сделать, пожалуйста, все скриншоты процесса, особенно 3 го пункта, так как после выхода из игры настройки возвращаются как были.

**Comment by albgr1979** [comment]
> Можете сделать, пожалуйста, все скриншоты процесса, особенно 3 го пункта, так как после выхода из игры настройки возвращаются как были.

I have already told you what you have to do.
If you want the changes to be saved, do this:

QUICK MENU - OVERRIDES - SAVE CONTENT DIRECTORY OVERRIDES

Please close the issue.

All the best
